### ISSUE TITLE
How to use the image if I already have a reverse proxy ?

### ISSUE THREAD

**Issue by MattiasGervilliers** [gravityfargo/bluesky-pds-docker#4]
Thanks for the image.
I already have a reverse proxy (nginx) that redirect bluesky.mydomain.com to my local ip on port 8000. 
What should i change in your image so it points to this ?
What's the goal of 
extra_hosts:
      - "example.com:0.0.0.0"

If i have a dynamic IP ?

**Comment by gravityfargo** [comment]
`extra_hosts` is only used for the `pdsadmin` command to resolve itself. You should be able to delete it when you're not using the command. I'll check that and get back to you.

**Comment by gravityfargo** [comment]
I did some testing and `extra_hosts` is not required unless you're using Cloudflare, which I advise against anyway. I updated the docs and you can safely remove those lines.

**Comment by MattiasGervilliers** [comment]
Thanks for your help. But I still don't understand how can I use my own reverse proxy (nginx here) to point to the bluesky pds (and don't use the one included).
